language: python
#python:
#  - "3"
services:
  - postgresql
# command to install dependencies
install:
  #- pip install --upgrade pip
  - pip install -r requirements.txt
 #command to run tests
before_script: # => 6
  #- source testenv/bin/activate
  #- sudo -i -u postgres
  - psql -c "CREATE USER root WITH PASSWORD 'passme';" -U postgres
  - psql -c "ALTER USER root CREATEDB;" -U postgres
script:
  - python manage.py test
deploy:
  provider: heroku
  api_key: 422debd3-0c66-4505-9b1a-2aeb97db4468
  app: sleepy-river-12079
  on:
    repo: Linonse/RSOI